# Generated by Django 4.2.16 on 2024-11-08 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('isActiveLobby', models.BooleanField(blank=True, default=True, null=True)),
                ('round', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('linkToJoin', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('lobbyWinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to='users.user')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player1', to='users.user')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player2', to='users.user')),
            ],
        ),
    ]
