# Generated by Django 4.2.16 on 2024-11-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(max_length=60)),
                ('isEliminated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
