# Generated by Django 4.2.16 on 2024-11-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('numberOfPlayers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isPrivate', models.BooleanField(blank=True, default=False, null=True)),
                ('difficultyLevel', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isActiveTournament', models.BooleanField(blank=True, default=False, null=True)),
                ('pointsPerGame', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('timer', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('powerUps', models.BooleanField(blank=True, default=False, null=True)),
                ('round', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tournamentWinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_tournament', to='users.user')),
            ],
        ),
    ]
